### ISSUE TITLE
disable features

### ISSUE THREAD

**Issue by abacaj** [thosakwe/flutter_music_player#2]
It would be nice if we could disable features.

For example, I would like to hide the track bar.
Some more customization would be ideal too, i.e reduce icon sizes.

Thanks!

**Comment by thosakwe** [comment]
Will gladly accept a PR for this.

**Comment by thosakwe** [comment]
I'm thinking that if `onShuffleChanged` is `null`, the shuffle button should not be displayed, and so on.
