### ISSUE TITLE
audio completes but doesn't reset play / pause icon

### ISSUE THREAD

**Issue by abacaj** [thosakwe/flutter_music_player#3]
When playing audio, and it finishes playing the player does not reset the play/pause icon to be play again.

Here is a screenshot: 
![screen shot 2018-04-08 at 1 21 44 am](https://user-images.githubusercontent.com/7272343/38463534-37a24ad2-3acb-11e8-8f7f-2aac419d6ac0.png)

**Comment by thosakwe** [comment]
Will gladly accept a PR for this as well.

Also, note that there is an `onCompleted` callback available for use.

```dart
class MyWidget extends StatelessWidget {
  final GlobalKey<MusicPlayerState> musicPlayerKey = new GlobalKey();

  @override
  Widget build(BuildContext ctx) {
    return new MusicPlayer(
      key: musicPlayerKey,
      onCompleted: () {
        key.currentState.audioPlayer.pause();
      },
      // ...
    );
  }
}
```
